# Generated by Django 5.2.5 on 2025-08-17 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("publica", "Pública"), ("privada", "Privada")],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Universidad",
                "verbose_name_plural": "Universidades",
                "db_table": "universities",
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("academica", "Académica"),
                            ("socioeconomica", "Socioeconómica"),
                            ("deportiva", "Deportiva"),
                            ("interna", "Interna"),
                        ],
                        max_length=20,
                    ),
                ),
                ("requisitos", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "universidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beca",
                "verbose_name_plural": "Becas",
                "db_table": "scholarships",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("area", models.CharField(max_length=100)),
                (
                    "plan_estudios_url",
                    models.URLField(
                        blank=True,
                        help_text="Link o PDF del plan de estudios",
                        null=True,
                    ),
                ),
                ("convocatoria_url", models.URLField(blank=True, null=True)),
                ("beca_disponible", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "universidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="universities.university",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa",
                "verbose_name_plural": "Programas",
                "db_table": "programs",
            },
        ),
    ]
