# Generated by Django 5.2.5 on 2025-08-17 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VocationalTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("resultado", models.CharField(max_length=255)),
                ("puntaje", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vocational_tests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Vocacional",
                "verbose_name_plural": "Tests Vocacionales",
                "db_table": "vocational_tests",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="VocationalAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                ("respuesta", models.TextField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="vocational.vocationaltest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta Vocacional",
                "verbose_name_plural": "Respuestas Vocacionales",
                "db_table": "vocational_answers",
            },
        ),
    ]
