# Generated by Django 5.2.5 on 2025-08-17 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lesson_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usercourseprogress",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_progress",
                to="learning.course",
            ),
        ),
        migrations.AddField(
            model_name="usercourseprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userlearningpath",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_paths",
                to="learning.learningpath",
            ),
        ),
        migrations.AddField(
            model_name="userlearningpath",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_paths",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="learningpathcourse",
            unique_together={("path", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="lessonprogress",
            unique_together={("user", "lesson")},
        ),
        migrations.AlterUniqueTogether(
            name="usercourseprogress",
            unique_together={("user", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="userlearningpath",
            unique_together={("user", "path")},
        ),
    ]
