# Generated by Django 5.2.5 on 2025-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VocationalAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                ("respuesta", models.TextField()),
            ],
            options={
                "db_table": "vocational_answers",
            },
        ),
        migrations.CreateModel(
            name="VocationalTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("resultado", models.CharField(max_length=255)),
                ("puntaje", models.IntegerField()),
            ],
            options={
                "db_table": "vocational_tests",
            },
        ),
    ]
